
package net.thucydides.maven.plugin.test.example;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 */
@WebServiceClient(name = "HelloWorldImplService", targetNamespace = "http://example.test.plugin.maven.thucydides.net/")
public class HelloWorldImplService
        extends Service {

    private final static URL HELLOWORLDIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.thucydides.maven.plugin.test.example.HelloWorldImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.thucydides.maven.plugin.test.example.HelloWorldImplService.class.getResource(".");
            url = new URL(baseUrl, "");
        } catch (MalformedURLException e) {
            logger.warning(e.getMessage());
        }
        HELLOWORLDIMPLSERVICE_WSDL_LOCATION = url;
    }

    public HelloWorldImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldImplService() {
        super(HELLOWORLDIMPLSERVICE_WSDL_LOCATION, new QName("http://example.test.plugin.maven.thucydides.net/", "HelloWorldImplService"));
    }

    /**
     * @return returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldImplPort")
    public HelloWorld getHelloWorldImplPort() {
        return super.getPort(new QName("http://example.test.plugin.maven.thucydides.net/", "HelloWorldImplPort"), HelloWorld.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldImplPort")
    public HelloWorld getHelloWorldImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.test.plugin.maven.thucydides.net/", "HelloWorldImplPort"), HelloWorld.class, features);
    }

}
