
package engagepoint.billing.paymentrequestservice._1;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PaymentRequestService", targetNamespace = "urn:engagepoint:billing:PaymentRequestService:1.0", wsdlLocation = "http://192.168.34.119:9080/billing/PaymentRequestService/PaymentRequestService.wsdl")
public class PaymentRequestService
    extends Service
{

    private final static URL PAYMENTREQUESTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(engagepoint.billing.paymentrequestservice._1.PaymentRequestService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = engagepoint.billing.paymentrequestservice._1.PaymentRequestService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.34.119:9080/billing/PaymentRequestService/PaymentRequestService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.34.119:9080/billing/PaymentRequestService/PaymentRequestService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PAYMENTREQUESTSERVICE_WSDL_LOCATION = url;
    }

    public PaymentRequestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentRequestService() {
        super(PAYMENTREQUESTSERVICE_WSDL_LOCATION, new QName("urn:engagepoint:billing:PaymentRequestService:1.0", "PaymentRequestService"));
    }

    /**
     * 
     * @return
     *     returns PaymentRequestServicePort
     */
    @WebEndpoint(name = "PaymentRequestWebServicePort")
    public PaymentRequestServicePort getPaymentRequestWebServicePort() {
        return super.getPort(new QName("urn:engagepoint:billing:PaymentRequestService:1.0", "PaymentRequestWebServicePort"), PaymentRequestServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentRequestServicePort
     */
    @WebEndpoint(name = "PaymentRequestWebServicePort")
    public PaymentRequestServicePort getPaymentRequestWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:engagepoint:billing:PaymentRequestService:1.0", "PaymentRequestWebServicePort"), PaymentRequestServicePort.class, features);
    }

}
